apiVersion: v1
kind: Service
metadata:
  name: jdtls-context-service-internal # this is the host of service
  labels:
    name: jdtls-context-service-internal
spec:
  ports:
  - port: 5036 # this is the host of service
    targetPort: 5036
  selector:
     app: jdtls-context