apiVersion: v1
kind: Service
metadata:
  name: jdtls-context-service-external # this is the host of service
  labels:
    name: jdtls-context-service-external
spec:
  type: NodePort
  ports:
  - port: 5036 # this is the host of service
    targetPort: 5036
    nodePort: 30536
  selector:
     app: jdtls-context